welcome_message: |
  Привет 🃏

  *Анализирую расклады Таро по фото*
  Честно, глубоко?

  ` - Пришли фото или текстовое описание своего расклада + вопрос для детального анализа.`
  ` - Или просто фото для расклада дня.`

agent_wait_message_with_photo: |
  Изучаю твое фото, подожди несколько секунд.

agent_wait_message_with_text: |
  Хорошо, дай подумать немного

bad_request_llm_reply:
  Извини, я сейчас не в духе, видимо звезды не расположены ко мне. Давай начнем сначала, отправь свой расклад заново.
