welcome_message: |
  Привет! 🃏

  Анализирую расклады Таро по фото.
  Честно, глубоко.

  - Пришли фото своего расклада + вопрос для детального анализа.
  - Или просто фото для расклада дня.

agent_wait_message_with_photo: |
  Изучаю твое фото, подожди несколько секунд.

agent_wait_message_with_text: |
  Хорошо, дай подумать немного

bad_request_llm_reply:
  Я сейчас не в духе, звезды не расположены ко мне сейчас. Отправь свой расклад заново.
